# -*- coding: utf-8 -*-
"""CSE602 Final Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18D3bLb2f_gHclJ1WP46xZqPlQPiofn7n

## Step 0: Get your packages in order.
"""

!pip install SimpleITK # This is a special library for visualising medical images.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import glob
import sklearn as skl
from skimage.transform import resize
import SimpleITK as sitk
import tensorflow as tf
from tensorflow import keras
import keras.backend as K
from keras import layers, Model

"""# 1. Download and Load the Training, Test and Validation Datasets

Data source: [BOston Neonatal Brain Injury Data](https://zenodo.org/records/10602767)

### *A Note on the Training Data* ###

The data consists of a special type of preprocessed MRI images, known as ADC maps.

*ADC: Apparent Diffusion Coefficient*
- It is a measure of the magnitude of diffusion (or movement) of water molecules across brain tissues.

- This molecular movement can be restricted due to structural damage in the brain, such as tumours or lesions.

- Areas where this happens tend to appear noticeably darker than surrounding areas on MRI images.

- These darker areas can help doctors to determine where these lesions or tumours could be located on the brain.

The ADC maps in the dataset have been categorised into three groups.

The first group contains raw, unedited, unprocessed images.

The second group comprises ADC maps that have undergone Z-score normalisation. This has been done to account for the fact that, under healthy conditions, different areas of the brain have different movement patterns of water molecules.

 So, Z-score normalisation is required to ensure that the movement of water molecules is compared across brain regions, according to each specific region's healthy baseline for molecular movement.

 The third group comprises binary masks of the images in which the brain lesions have been manually annotated by trained physicians.

 More information can be found on these pages:

 [Bao et al., 2023](https://www.biorxiv.org/content/10.1101/2023.06.30.546841v1.full)

 [Radiopaedia - Apparent Diffusion Coefficient](https://radiopaedia.org/articles/apparent-diffusion-coefficient-1)
"""

from google.colab import drive
drive.mount('/content/drive')

!unzip -q /content/drive/MyDrive/CSE602_Project_Data/train_data.zip
!unzip -q /content/drive/MyDrive/CSE602_Project_Data/val_data.zip
!tar -xvf /content/drive/MyDrive/CSE602_Project_Data/atlases.tar.gz
#!unzip -q /content/drive/MyDrive/CSE602_Project_Data/test_data.zip

#Some basic EDA; we read in and visualise the first five raw ADC maps to get a glimpse of the data we'll be dealing with.


train_dir = '/content/BONBID2023_Train'

for i in [10, 14, 15, 28, 62]:
  train_image = sitk.ReadImage(f"{train_dir}/1ADC_ss/MGHNICU_0{i}-VISIT_01-ADC_ss.mha")
  train_array = sitk.GetArrayFromImage(train_image)
  mid_slice = train_array.shape[0] // 2

  plt.figure(figsize=(8, 6))
  plt.imshow(train_array[mid_slice, :, :], cmap = 'gray')
  plt.title(f"Image {i}")
  plt.axis('off')
  plt.show()
  print(train_image.GetSize())

# We do the same for the Z-score normalised ADC maps...

for i in [10, 14, 15, 28, 62]:
  train_image = sitk.ReadImage(f"{train_dir}/2Z_ADC/Zmap_MGHNICU_0{i}-VISIT_01-ADC_smooth2mm_clipped10.mha")
  train_array = sitk.GetArrayFromImage(train_image)
  mid_slice = train_array.shape[0] // 2

  plt.figure(figsize=(8, 6))
  plt.imshow(train_array[mid_slice, :, :], cmap = 'gray')
  plt.title(f"Image {i}")
  plt.axis('off')
  plt.show()
  print(train_image.GetSize())

# ...and for the binary image masks with brain lesions annotated by experts.
for i in [10, 14, 15, 28, 62]:
  train_image = sitk.ReadImage(f"{train_dir}/3LABEL/MGHNICU_0{i}-VISIT_01_lesion.mha")
  train_array = sitk.GetArrayFromImage(train_image)
  mid_slice = train_array.shape[0] // 2

  plt.figure(figsize=(8, 6))
  plt.imshow(train_array[mid_slice, :, :], cmap = 'gray')
  plt.title(f"Image {i}")
  plt.axis('off')
  plt.show()
  print(train_image.GetSize())

file_path = '/content/atlases/lesion_atlases/readme.txt'

with open(file_path, 'r') as file:
  content = file.read()

content

norm_path= '/content/atlases/normal_atlases/readme_normal_atlases.txt'

with open(norm_path, 'r') as file:
  norm_content = file.read()

norm_content

"""##2. Read in and Preprocess the Training Data

In order to build a model that uses multimodal data, using the ADC and ZADC maps as two separate modalities, we need to stack the ADC and ZADC maps to obtain the final training set.
"""

# First, we define a helper function to read in all the images from the directory sequentially.
def load_images(directory_path):
    image_list = []
    filepaths = sorted(glob.glob(os.path.join(directory_path, '*.*')))

    for filepath in filepaths:
        sitk_img = sitk.ReadImage(filepath)
        img_array = sitk.GetArrayFromImage(sitk_img)
        image_list.append(img_array)

    return np.concatenate(image_list, axis=0)

# We use our helper function to load in and prepare the feature and target data.

adc_train = load_images('/content/BONBID2023_Train/1ADC_ss')
zadc_train = load_images('/content/BONBID2023_Train/2Z_ADC')

X_train = np.stack((adc_train, zadc_train), axis = 1)
y_train = load_images('/content/BONBID2023_Train/3LABEL')
y_train = np.expand_dims(y_train, axis = -1)

"""##3. Build and Train the Model

The chosen model architecture is the [2.5D Transformer Backbone U-Net Model](https://www.mdpi.com/2076-3425/15/8/778#:~:text=To%20evaluate%20the%20effectiveness%20of,diagnostic%20tools%20in%20clinical%20settings.).


This architecture has been chosen as it has achieved a Dice score of 0.8153 while segmented brain lesions in stroke patients.


The detailed rationale for this choice of architecture may be found in the explanatory project idea presentation which has been uploaded to this repository.


The following model architecture is a baseline architecture to implement this model. Parameters will be edited according to the model's performance on initial runs.
"""

def transformer_block(x, num_heads = 4, key_dim = 128, mlp_dim = 256, dropout = 0.1):
    attn_out = layers.MultiHeadAttention(num_heads=num_heads, key_dim=key_dim)(x, x)
    attn_out = layers.Dropout(dropout)(attn_out)
    x = layers.Add()([x, attn_out])
    x = layers.LayerNormalization(epsilon=1e-6)(x)

    mlp_out = layers.Dense(mlp_dim, activation='gelu')(x)
    mlp_out = layers.Dense(x.shape[-1])(mlp_out)
    mlp_out = layers.Dropout(dropout)(mlp_out)
    x = layers.Add()([x, mlp_out])
    x = layers.LayerNormalization(epsilon=1e-6)(x)
    return x

def build_2_5d_transunet(input_shape=(128, 128, 23), num_classes = 1):
    inputs = layers.Input(shape=input_shape)

    c1 = layers.Conv2D(128, 3, activation='relu', padding='same')(inputs)
    c1 = layers.Conv2D(128, 3, activation='relu', padding='same')(c1)
    p1 = layers.MaxPooling2D()(c1)

    c2 = layers.Conv2D(128, 3, activation='relu', padding='same')(p1)
    c2 = layers.Conv2D(128, 3, activation='relu', padding='same')(c2)
    p2 = layers.MaxPooling2D()(c2)

    shape = p2.shape
    patch_dim = shape[-1] # 128
    flattened = layers.Reshape((shape[1] * shape[2], patch_dim))(p2)

    t1 = transformer_block(flattened)
    t2 = transformer_block(t1)

    t_feat = layers.Reshape((shape[1], shape[2], patch_dim))(t2)
    t_feat = layers.Conv2D(128, 3, padding='same', activation='relu')(t_feat)

    u_block1 = layers.Conv2DTranspose(128, 2, strides=2, padding='same')(t_feat)
    u_block1 = layers.concatenate([u_block1, c2])
    conv_block1 = layers.Conv2D(128, 3, activation='relu', padding='same')(u_block1)
    conv_block1 = layers.Conv2D(128, 3, activation='relu', padding='same')(conv_block1)

    u_block2 = layers.Conv2DTranspose(128, 2, strides=2, padding='same')(conv_block1)
    u_block2 = layers.concatenate([u_block2, c1])
    conv_block2 = layers.Conv2D(128, 3, activation='relu', padding='same')(u_block2)
    conv_block2 = layers.Conv2D(128, 3, activation='relu', padding='same')(conv_block2)

    outputs = layers.Conv2D(num_classes, 1, activation='sigmoid')(conv_block2)

    return Model(inputs, outputs)

model = build_2_5d_transunet()
model.summary()

# We need to define a helper function to calculate the Dice coefficient as Keras does not provide this as a built-in metric.
def dice_coef(y_true, y_pred, smooth=1):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)

    intersection = K.sum(y_true_f * y_pred_f)
    union = K.sum(y_true_f) + K.sum(y_pred_f)

    dice = (2. * intersection + smooth) / (union + smooth)
    return dice

# We also require a hybrid loss function to account for class imbalance in the training set.
# This helper function combines the Dice Loss and Focal Loss.

dice_loss = keras.losses.Dice()
bce_focal_loss = keras.losses.BinaryFocalCrossentropy()

def hybrid_loss(y_true, y_pred):
  dice = dice_loss(y_true, y_pred)
  focal = bce_focal_loss(y_true, y_pred)
  return dice + focal

model.compile(optimizer = keras.optimizers.Adam(learning_rate = 0.001), loss = hybrid_loss, metrics = [dice_coef, 'accuracy'])

